### ISSUE TITLE
Typo and text improvement suggestion

### ISSUE THREAD

**Issue by bpires** [Guss-droid/gustavodev#3]
Fala Gustavo, na sua descrição detectei um erro de digitação:
> Inicialmente ~comece~ com => **comecei** com...

Além do que acho que JS, HTML e CSS ficam melhor em maiúsculas (por serem siglas abreviadas).

Se me permite, deixo aqui uma sugestão para dar um up no teu texto:

> Tenho 17 anos e estudo programação desde o final de 2020, quando tinha apenas 15. Naquela época, fui à fundo em HTML e CSS e comecei a me aventurar em Javascript. Hoje, muito estudo e vários projetos depois, minhas stacks preferidas incluem React, React Native, Next.jse e Node.js, além de diversas outras ferramentas e tecnologias que incorporei ao meu dia-a-dia como desenvolvedor.

Grande abraço e sucesso!

**Comment by Guss-droid** [comment]
Fala Rafa, Fiz as alterações do texto, em questão ao bug estou vendo a melhor maneira de responder,

Abraço!
