### ISSUE TITLE
Bug on stack's cards visualization

### ISSUE THREAD

**Issue by bpires** [Guss-droid/gustavodev#4]
Hey gustavo,

Ao clicarmos nos cards das stacks, a depender do tamanho do texto descritivo, há uma alteração indesejada no layout.

![image](https://user-images.githubusercontent.com/86871991/177684530-6971c186-fc3b-4578-88ea-5390baa22eab.png)

![image](https://user-images.githubusercontent.com/86871991/177684723-b298d916-310f-4911-8393-d4bd020a1a4f.png)

Minha sugestão é você travar o tamanho máximo de texto e manter o quadro descritivo em um tamanho fixo que seja suficiente para envolvê-lo, evitando esse efeito.

Grande abraço!

**Comment by Guss-droid** [comment]
Opa Rafa, beleza?

Arrumei a visualização dos cards. Obrigado pelo aviso

Abraço!
